# Generated by Django 5.2.8 on 2025-11-15 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="DeliveryProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "vehiculo",
                    models.CharField(
                        choices=[
                            ("Bicicleta", "Bicicleta"),
                            ("Moto", "Moto"),
                            ("Auto", "Auto"),
                            ("Caminando", "Caminando"),
                        ],
                        default="Caminando",
                        max_length=50,
                    ),
                ),
                ("disponible", models.BooleanField(default=True)),
                (
                    "rating_promedio",
                    models.DecimalField(decimal_places=2, default=5.0, max_digits=3),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Perfil de Repartidor",
                "verbose_name_plural": "Perfiles de Repartidores",
            },
        ),
    ]
