# Generated by Django 5.2.8 on 2025-11-11 16:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("market", "0001_initial"),
        ("users", "0002_clienteprofile_ferianteprofile_repartidorprofile"),
    ]

    operations = [
        migrations.AddField(
            model_name="ferianteprofile",
            name="feria_asignada",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="market.feria",
            ),
        ),
    ]
