# Generated by Django 5.2.8 on 2025-11-15 21:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("market", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="puesto",
            name="feriante",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="puestos",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="producto",
            name="puesto",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="productos",
                to="market.puesto",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="puesto",
            unique_together={("feria", "nombre")},
        ),
    ]
