# Generated by Django 5.2.8 on 2025-12-10 16:17

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("market", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="producto",
            name="image",
            field=cloudinary.models.CloudinaryField(
                blank=True, max_length=255, null=True, verbose_name="image"
            ),
        ),
    ]
