# Generated by Django 5.2.8 on 2025-11-15 21:50

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("CREADO", "Creado"),
                            ("CONFIRMADO", "Confirmado"),
                            ("EN_PREPARACION", "En Preparación"),
                            ("LISTO", "Listo para Entrega"),
                            ("EN_CAMINO", "En Camino"),
                            ("ENTREGADO", "Entregado"),
                            ("CANCELADO", "Cancelado"),
                        ],
                        default="CREADO",
                        max_length=20,
                    ),
                ),
                (
                    "total",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                ("notas", models.TextField(blank=True, null=True)),
                (
                    "ubicacion_repartidor",
                    models.CharField(
                        blank=True,
                        help_text="Última latitud/longitud conocida del repartidor.",
                        max_length=255,
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Pedido",
                "verbose_name_plural": "Pedidos",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="OrderItem",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("cantidad", models.PositiveIntegerField(default=1)),
                (
                    "precio_unitario",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Precio del producto al momento de la compra",
                        max_digits=10,
                    ),
                ),
                (
                    "subtotal",
                    models.DecimalField(
                        decimal_places=2, editable=False, max_digits=10
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Item de Pedido",
                "verbose_name_plural": "Items de Pedido",
            },
        ),
    ]
