# Generated by Django 5.2.8 on 2025-11-16 14:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0003_alter_orderitem_subtotal_payment"),
    ]

    operations = [
        migrations.CreateModel(
            name="PaymentLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("received_at", models.DateTimeField(auto_now_add=True)),
                (
                    "provider",
                    models.CharField(
                        blank=True,
                        help_text="Nombre de la pasarela (ej: mercadopago, flow)",
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "provider_ref",
                    models.CharField(
                        blank=True,
                        help_text="ID del evento o pago en la pasarela",
                        max_length=200,
                        null=True,
                    ),
                ),
                (
                    "payload",
                    models.JSONField(
                        help_text="Datos completos del webhook/evento recibido"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        default="RECEIVED",
                        help_text="Estado interno del procesamiento del log",
                        max_length=50,
                    ),
                ),
                (
                    "handled",
                    models.BooleanField(
                        default=False,
                        help_text="Indica si ya fue procesado por el sistema",
                    ),
                ),
            ],
            options={
                "verbose_name": "Registro de Pago",
                "verbose_name_plural": "Registros de Pagos",
                "ordering": ["-received_at"],
            },
        ),
        migrations.AddField(
            model_name="payment",
            name="provider",
            field=models.CharField(
                blank=True,
                help_text="Nombre de la pasarela (ej: mercadopago, flow)",
                max_length=50,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="payment",
            name="provider_ref",
            field=models.CharField(
                blank=True,
                help_text="ID único del pago en la pasarela externa",
                max_length=200,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="payment",
            name="metodo",
            field=models.CharField(
                help_text="Método de pago (ej: EFECTIVO, TRANSBANK, MERCADOPAGO)",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="payment",
            name="order",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="payment",
                to="orders.order",
            ),
        ),
    ]
