# Generated by Django 5.2.8 on 2025-11-16 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0005_alter_payment_options_alter_payment_order"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="payment",
            constraint=models.UniqueConstraint(
                condition=models.Q(("provider_ref__isnull", False)),
                fields=("provider", "provider_ref"),
                name="unique_provider_provider_ref_not_null",
            ),
        ),
    ]
