# Generated by Django 5.2.8 on 2025-11-16 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0006_payment_unique_provider_provider_ref_not_null"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="paymentlog",
            constraint=models.UniqueConstraint(
                fields=("provider", "provider_ref"), name="uq_paymentlog_provider_ref"
            ),
        ),
    ]
