# Generated by Django 5.2.8 on 2025-12-10 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0007_paymentlog_uq_paymentlog_provider_ref"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="direccion_envio",
            field=models.CharField(
                blank=True,
                help_text="Dirección física para la entrega (usada en mapas).",
                max_length=255,
                null=True,
            ),
        ),
    ]
